### ISSUE TITLE
Not working with newest firmware version 3.3.9_003073

### ISSUE THREAD

**Issue by ultrara1n** [rytilahti/python-mirobo#14]
Using this great code till today, after Xiaomi had to change the way of communication. 
Getting the following result when just trying to get info data from vacuum:

> ERROR:mirobo.vacuum:got error when receiving: timed out
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mirobo/cli.py", line 46, in cli
    ctx.invoke(status)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mirobo/cli.py", line 59, in status
    res = vac.status()
  File "/usr/local/lib/python3.4/dist-packages/mirobo/vacuum.py", line 150, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/usr/local/lib/python3.4/dist-packages/mirobo/vacuum.py", line 121, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

**Comment by jcastro** [comment]
umm it's working for me! maybe the token changed or something else?

**Comment by ultrara1n** [comment]
Have you updated your vacuum to the latest Firmware version? According to http://www.roboter-forum.com/showthread.php?18995-Neues-Firmware-Update!&p=254656&viewfull=1#post254656 there was a change for the sent packages to the robot. They are now signed with a timestamp to dismiss too old packages. The token haven't changed, because the App of the User from the linked Post ist already working, after updating to the newest Version.

**Comment by SchumyHao** [comment]
@rytilahti  I think you can take a look my pull request. I fixed the timestamp issue

**Comment by jcastro** [comment]
@ultrara1n yeah I did (see image below). Aside from these errors, which I was getting them before the update, everything seems to work as usual

`2017-06-07 10:17:28 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x2ba90ccbed30>_5) [mirobo.vacuum] got error when receiving: timed out
2017-06-07 10:17:28 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x2ba90ccbed30>_5) [custom_components.switch.xiaomi_vacuum] Got exception while fetching the state: timed out`

![img_5502](https://user-images.githubusercontent.com/190036/26870287-cadc9812-4b6f-11e7-9594-1d9187f01d90.PNG)

**Comment by rytilahti** [comment]
@jcastro maybe your clock on the vacuum is also in correct time? Currently we are sending the current timestamp out, which could explain why it is working.

@SchumyHao do you mind rebasing that change on the current HEAD, or should I just incorporate "replaying" the device timestamp + some short delay?

**Comment by jcastro** [comment]
@rytilahti umm just checked it and it seems fine! Also checked my docker installation and it's also correct

```bash
root@unBeast:/usr/src/app# date
Wed Jun  7 12:14:25 CEST 2017
root@unBeast:/usr/src/app# 
```

**Comment by rytilahti** [comment]
@jcastro yes, does the robot return something similar? (when doing mirobo -d or -dd) In my case mine (which has no internet access) says: ts = 1970-01-01 15:55:39

**Comment by SchumyHao** [comment]
@rytilahti  I'll create a new pull request later.
Because after you refactoring the code, my early pull request has merge conflict.

**Comment by rytilahti** [comment]
@SchumyHao ok, thanks! Please also take a note on my commentary on the code parts. I think it should be enough just to save the timestamp returned in responses and increment it with timedelta for a bit.

**Comment by jcastro** [comment]
@rytilahti yep!
```bash
value = Container: 
            length = 80
            unknown = 0
            devtype = 791
            serial = 62472
            ts = 2017-06-07 12:31:32
```

**Comment by chrostek** [comment]
any news here? my mirobo still does not work with this script with firmware 3.3.9 (worked with older one).
the patch from rytilahti also does not work for me. with the original script the 
ts is correct (localtime), with the patch from rytilahti the ts is+2h (utc+4, localtime+2) my localtime is "Europe/Berlin (CEST, +0200)"

**Comment by chrostek** [comment]
https://github.com/ioBroker/ioBroker.mihome-vacuum/commit/2e28df0c43f9763bfeadd95b9cbf8f3db38b5d1b

it seems that there was a protocol change with 3.3.9

**Comment by chrostek** [comment]
@ultrara1n can you try to discover the token via one of this ways: https://github.com/ioBroker/ioBroker.mihome-vacuum#konfiguration
in my case the token discovered via the python script was wrong (i have done a complete reset and discovered new after the firmware update). the token in the sqlite database (iOS) was another one. with the other one the communication works again ...

**Comment by ultrara1n** [comment]
@chrostek: I'm the creator of the MiToolkit (see my repo) :D
But I think It could have something to do with my raspberry, will try it on Windows later.

**Comment by rytilahti** [comment]
@chrostek, There's #15 which does seem to work sometimes but I haven't been able to make it work consistently all the time, so I'm still looking for a proper way to fix this.

**Comment by chrostek** [comment]
@rytilahti i moved to:
https://marketplace.eclipse.org/content/openhab-xiaomi-vacuum-binding
it works with the token from the sqlite db from iOS. the python script does not work anymore. but i dont need it anymore. thanks for the info

**Comment by rytilahti** [comment]
@chrostek glad to hear you got it working. Looks like it's not anymore possible to read the token out from the robot itself.

Anyway, thanks to #21 I realized that the id generation is the problem and I got the cli tool working again by not reusing the same 'id' for communication (the robot answers once per 'id' in a specific time-frame.

**Comment by TribuneX** [comment]
So for now there is no way to get the token with the latest firmware anymore. To bad that I just updated before extracting it.

**Comment by rytilahti** [comment]
@TribuneX you can supposedly still extract the token from already paired device but I have not tested out.

**Comment by TribuneX** [comment]
@rytilahti Do you have a link to some documentation who I can extract it from paired devices. I am using the iOS app.

**Comment by rytilahti** [comment]
@TribuneX some possible ways can be seen in this issue: https://github.com/aholstenson/miio/issues/40#issuecomment-309224708

**Comment by TribuneX** [comment]
@rytilahti Thanks! I was able to extract the token from the sqlite file within my iOS backup.
