### ISSUE TITLE
Xiaomi vaccum control from Raspberry pi + iPad Mi app at the same time - token: b'ffffffffffffffffffffffffffffffff'

### ISSUE THREAD

**Issue by alexdom** [rytilahti/python-mirobo#16]
First of all, thanks for a great software! 

So long I am trying to get my Xiaomi Mi Vaccum robot to work with **_mirobo_** on my Raspberry Pi 2 (Debian Jessie, Ethernet connection + USB Wi-Fi). 

Initially, I connected my Xiaomy Mi Vacuum and three Air Purifiers to home Wi-Fi  so I could control it via iPad Mi app. I can use **_mirobo_** then to discover all their tokens from command line:

`-> # mirobo discover `  
```
INFO:mirobo.vacuum:Sending discovery to <broadcast> with timeout of 5s..
INFO:mirobo.vacuum:  IP 192.168.0.22: 833 - token: b'7eda8d580fa5c33dbb6168326f75efbd'
INFO:mirobo.vacuum:  IP 192.168.0.23: 830 - token: b'4e65fb7827d51cd2208f0acdf9af7b08'
INFO:mirobo.vacuum:  IP 192.168.0.24: 833 - token: b'79f795f4d8db427a1946f93e6c610fcb'
INFO:mirobo.vacuum:  IP 192.168.0.25: 847 - token: b'ffffffffffffffffffffffffffffffff'
INFO:mirobo.vacuum:Discovery done
```
So, I reset Mi Vacuum and get RPi connected to Vacuum Wi-Fi by wlan0 USB adapter. Only then I could define Vacuum token and have it controlled via command line:

`-> # mirobo discover`
```
INFO:mirobo.vacuum:Sending discovery to <broadcast> with timeout of 5s..
INFO:mirobo.vacuum:  IP 192.168.4.1: 847 - token: b'7a3779494c6d5679a475496f42646344'
INFO:mirobo.vacuum:Discovery done
```
`> # export MIROBO_IP=192.168.4.1`
`> # export MIROBO_TOKEN=7a3779494c6d56793475496f42646344 `
`> # mirobo`
```
State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 0:00:02
Cleaned area: 0.0 m²
DND enabled: 0
```

But then, Vacuum looses connection to home Wi-Fi. And I can't control one from iPad at the same time.

  
...........  
So I have two questions:

1) Why Xiaomi Mi Vacuum can't be discovered in local network as well as Air Purifiers?  

2) Is it possible to control Xiaomi Mi Vacuum from Rpi command line and from iPad Mi app at the same time?

**Comment by rytilahti** [comment]
Did you try to connect it again with the iPad after fetching the token? That's the way it should work; the token will be only available before the device has been configured with a device, however, I have just tested this on Android.

**Comment by alexdom** [comment]
Yep! It worked! Thanks a lot!
`-> # mirobo discover`
```INFO:mirobo.vacuum:Sending discovery to <broadcast> with timeout of 5s..
INFO:mirobo.vacuum:  IP 192.168.4.1: 847 - token: b'4c66774d6b544d513548743854597653'
INFO:mirobo.vacuum:Discovery done
```
Then I connected my Xiaomy Mi Vacuum to home Wi-Fi via iPad Mi app and tried it again but with local home IP and a token obtained above. It worked:
`mirobo --ip=192.168.0.25 --token=4c66774d6b544d513548743854597653`
```State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 1:04:27
Cleaned area: 53.5575 m²
DND enabled: 0
```

**Comment by rytilahti** [comment]
Good to hear, closing this then.
