### ISSUE TITLE
mirobo "DND enabled: 0", after change to 1

### ISSUE THREAD

**Issue by alexdom** [rytilahti/python-mirobo#18]
I try to set DND mode, when query status, it still shows DND 0:

```
-> # mirobo dnd on 20 0 8 0
Enabling DND 20:0 to 8:0
0
```
```
-> # mirobo dnd 1          
DND 21:00 to 08:00 (enabled: 1)
```

```
-> # mirobo                
State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 0:00:02
Cleaned area: 0.0 m²
DND enabled: 0
```

**Comment by rytilahti** [comment]
What happens if you just type "mirobo dnd"? I think the status message the robot is giving out is incomplete, and needs to be adjusted.

**Comment by alexdom** [comment]
`-> # mirobo dnd`
`DND 20:00 to 08:00 (enabled: 1)`

**Comment by marcelrv** [comment]
I think the status DND is if currently DND is active or not not.
The value in DND message is if the DND functionality is enabled.

https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/dnd_timer.md

**Comment by rytilahti** [comment]
Yes, the one in status (what comes up as default) is from the payload returned for status requests. I should probably just hide it for now.
