### ISSUE TITLE
can't find my robot

### ISSUE THREAD

**Issue by brianping7** [rytilahti/python-mirobo#2]
i did by following step
1. remove the robot from app, and reset the robot
2. join the network through my laptop
3. run discover 
4. i got time out, and no device is found, even i increase the timeout time to 20

thanks for the help

**Comment by rytilahti** [comment]
I can't think of any reason why this wouldn't work. One possible thing (which is more involving) you could try is to use wireshark to capture the network traffic while connecting the robot through the app. This way you could see if the messaging looks correct.

**Comment by rytilahti** [comment]
I changed the discovery process to send more packets, maybe that helps? Please upgrade and test again.

**Comment by brianping7** [comment]
i again run the script on linux, and it's working. previously i run it on the windows...maybe because of my firewall setting. thanks for the help.
