### ISSUE TITLE
Feature request: show cleaning map

### ISSUE THREAD

**Issue by cnberg** [rytilahti/python-mirobo#20]
Thanks for your excellent job! 

Sometimes I have to use the mihome app, check the map to know the cleaning status.So if possible you can provide the cleaning map( or the waypoints to help me to build the map).

**Comment by cnberg** [comment]
One more question, what is get_map_v1 for? 

I tried with `raw_command`, got:

> mirobo raw_command get_map_v1
> Sending cmd get_map_v1 with params []
> ['retry']

**Comment by rytilahti** [comment]
Retry just means that your robot can't fetch something from their servers. I have no idea how the map is supposed to work but I assume its done on the server-side and I'm unsure how easy it would be to replicate it when wanted.

**Comment by rytilahti** [comment]
Closing this as there's nothing we can do without deciphering the protocol between device<->app<->cloud combination.
