### ISSUE TITLE
Pause not working in remote control mode

### ISSUE THREAD

**Issue by Luftloch80** [rytilahti/python-mirobo#26]
Command pause only working during auto cleaning

**Comment by rytilahti** [comment]
Manual controls are completely separated from other functionalities, that's why they are also hidden behind a separate command.

**Comment by rytilahti** [comment]
If you have proposals / ideas how this should work, please reopen, I consider this something which is not in the scope of the library and should be handled by the user of the lib. Normal mode and manual mode are completely separated, and I don't really want to introduce any kind of extra magic there.
