### ISSUE TITLE
Philips Bulb and ceiling how to get token ?

### ISSUE THREAD

**Issue by deennoo** [rytilahti/python-mirobo#42]
Hi there fantastic works, only have a philips xiaomi bulb for now, Just wonder how to find token ?

`mirobo discover` doesn't result any thing execpt my 3 yeelight and my gateway

`miceil discover need --ip 192.168.0.208 --token false token` to show something 

As this bulb looks to have same fonction as the ceiling, just want to test, can you help ?

Thanks

**Comment by rytilahti** [comment]
Hi, I just merged a PR adding a comment about how to get the token, see https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token_mirobot_new.md . The same procedure should work fine for those lights too.

**Comment by deennoo** [comment]
Ok done and confirming it works ! thank you !
