### ISSUE TITLE
Allow sending discovery packets to static IP address

### ISSUE THREAD

**Issue by FabioDeMiranda** [rytilahti/python-mirobo#5]
Hi there! 

I reset the WIFI pressing the home and power buttons, after that I pressed the reset, but in both cases I'm getting the same message:

mirobo discover
INFO:mirobo.vacuum:Sending discovery packet to <broadcast> with timeout of 5s..
INFO:mirobo.vacuum:Discovery done

I'm using a Windows 10 machine with python 3.6.1 , I scanned with nmap the vacuum IP (192.168.8.1) and it seems the only ports open are 22 and 53... Am I missing something?

Thanx for creating this script and integrating with HA!

**Comment by rytilahti** [comment]
Hi, that's odd. Maybe the robot just wasn't responding to those discovery packets? Could you try it again multiple times, for some reason the vacuum does not always answer to those calls but I'm not sure what's the cause for it.

**Comment by FabioDeMiranda** [comment]
I tried it from the raspberry PI I have HA and it's happening the same thing...

I can ping the vacuum and I tried to ssh, but I'm getting "ssh: connect to host 192.168.8.1 port 22: Connection timed out". 

I didn't read the post you used to create the script or took a look at you code, so I don't know what I should expect.

What I can say is that I did upgrade the firmware the first time I used the app...

**Comment by rytilahti** [comment]
The vacuum doesn't accept incoming connections, port 54321 is the only way currently to communicate with them. You could try to see with wireshark if the device responds something to those discovery packets, other than that I can't really help without more information.

**Comment by FabioDeMiranda** [comment]
I had to change s.sendto(helobytes, (addr, 54321)) to s.sendto(helobytes, ('192.168.8.1', 54321)) and get the response on wireshark, after that I could use the token with everything else... I'll try the HA integration now.

Thanx anyway!

**Comment by rytilahti** [comment]
Nice to hear you got it working, did you get it working with that on Windows or on Raspberry pi?

**Comment by FabioDeMiranda** [comment]
After getting the token from wireshark it's working on both and on HA.

**Comment by pulse-mind** [comment]
Hi, I am trying to discover it but I have the same behavior : 
INFO:mirobo.vacuum:Sending discovery packet to with timeout of 5s..
INFO:mirobo.vacuum:Discovery done

I am using windows 10 with pycharm, python 3.6 in a virtualenv.
I reset wifi on vacuum and I reset the vacuum. I connected my wifi laptop to the rockrobo-xxxx. Then under pycharm (virtualenv) I did the discover. 

I tried many times. I tried to set the timeout to 20s but nothing better.

I can try something with wireshark but I am not confident with it.

**Comment by rytilahti** [comment]
This sounds like that <broadcast> is not working correctly on windows (10?), so I'll reopen this for now. Unfortunately I have no time to put into this, but maybe someone with a windows installation can help me out?

Another possibility would be to just "broadcast" the message to that static IP for now but I feel that's the wrong way to do it (although sofar this IP has been always used by this vacuum afaik).

**Comment by pulse-mind** [comment]
Thank you for your anwser, I tried with "Ubuntu for windows", I tried with
a VirtualMachine Ubuntu : nothing works. I am going to try with a live
Ubuntu.

**Comment by pulse-mind** [comment]
So I set-up ubuntu on another drive and it works.

Le sam. 29 avr. 2017 à 11:55, Pulse Mind <pulse.mind.com@gmail.com> a
écrit :

**Comment by pulse-mind** [comment]
Otherwise with windows 10 the easiest way is to :
* reset wifi on the vacuum (press both button on the vacuum)
* reset the vacuum
* connect to the wifi of the pc to the wifi of the vacuum (rockrobo-xxxx)
* open packet sender (portable)
* set the ip : 192.168.8.1, hex :
21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff,
port : 54321, Protocol : UDP
* send
* In the answer as hex takes the last 16 characters (do not count white
spaces). This is the token.
* switch to your wifi
* use your mobile phone and mihome app to set-up the vacuum
* then you can use mirobo python to get values... (use export to set the IP
of the vacuum on the wifi and to set the token or use --ip and --token)

Le sam. 29 avr. 2017 à 11:54, Pulse Mind <pulse.mind.com@gmail.com> a
écrit :

**Comment by rytilahti** [comment]
Ok. As the robot is always on that given IP, maybe it makes sense at least to allow using a static IP for the discovery, so let's keep this issue open.

**Comment by 1043717432** [comment]
@pulse-mind  @FabioDeMiranda  The same problem, the use of windows10 under the following PIP3 virtualenv interface error. I have reset the vacuum, I would like to ask you how to solve it? Please tell me the order, thank you!
Error condition:
INFO:mirobo.vacuum:Sending discovery <broadcast> with timeout of to 5s..
WARNING:mirobo.vacuum:error while discover results: 22] Invalid [Errno reading argument

**Comment by pulse-mind** [comment]
I do not know how to do the discover with python and how to adapt this code. 
But I explained another solution to get the token. Have a look in the previous messages.

**Comment by 1043717432** [comment]
@pulse-mind 
Thank you, I am sorry, I read the news or do not understand what the use of tools or applications to get the token, you can step in detail the steps?

**Comment by pulse-mind** [comment]
The tool here is great. It can does a discover = display the token. And then it can get the information of the vaccum and send commands. But to get the information and to send commands, you need the token. The token is used to encrypt and decrypt the command. Without the token it is "impossible" to communicate with the vacuum. 
In my previous comments I explained how to do it with windows 10. I am using a software called "packet sender" to send packets to an IP (the IP of the vacuum after a reset).

**Comment by 1043717432** [comment]
@pulse-mind  Thank you. I'll try it when I get home! Thanks for reply!

**Comment by 1043717432** [comment]
@pulse-mind  * open packet sender (portable) * hex:21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffff, port:54321, ip:192.168.8.1, protocol: UDP * send * in sixteen hexadecimal answer, the last 16 characters (not counting spaces).
Is this a step? Is to send hex:21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffff???

**Comment by pulse-mind** [comment]
yes. 
Be sure to switch your wifi connexion to the wifi of the robot not your usual wifi otherwise it won't work. 
The robot will answer by providing its token in the answer

**Comment by 1043717432** [comment]
@rytilahti  Thank you！！ The article said that yesterday to see over the notebook computer can install the Mi application can capture. I haven't tested it yet!

**Comment by 1043717432** [comment]
@pulse-mind  Hello Take out the blanks. I finally found the export MIROBO_TOKEN=2131002000000000034D5249000107B0766B5169566D6B51307350484C574A48, right? What numbers are reserved? Do I need to convert?

**Comment by 1043717432** [comment]
@FabioDeMiranda @pulse-mind @rytilahti  Is it possible to store custom_components\switch\mirobo.py separately? Do I need to include python-mirobo-master\mirobo and deposit it? Where is it?

**Comment by 1043717432** [comment]
@pulse-mind  Thank you It has been successful!

**Comment by rytilahti** [comment]
Considering that the new discovery is done over mDNS, and that the "handshake" discovery is sent to the given IP when executing any commands, I think this can be closed now.
