### ISSUE TITLE
Error in new mirobo/protocol.py

### ISSUE THREAD

**Issue by SelmaUrban** [rytilahti/python-mirobo#54]
Hello rytilahti,
the new protocol.py caused an error:
>  File "/mirobo/protocol.py", line 42, in verify_token
>     raise ValueError("Token must be of length 32")
> ValueError: Token must be of length 32

This is the code block:
```
    @staticmethod
    def verify_token(token: bytes):
        if not isinstance(token, bytes):
            raise TypeError("Token must be bytes")
        if len(token) != 32:
            raise ValueError("Token must be of length 32")
```
I think
> if len(token) != 32:

must be

> if len(token) != 16:

because of "bytes".

---
Short question:
Why is
    # click.echo("DND enabled: %s" % res.dnd)
    # click.echo("Map present: %s" % res.map)
    # click.echo("in_cleaning: %s" % res.in_cleaning)
comment out in vacuum_cli.py?

---

Greetings

**Comment by rytilahti** [comment]
Ah, sorry, I missed that, thanks for noticing. Regarding to your question, those values are in the response from the vacuum but they are not useful or accurate based on my own experiences.
