### ISSUE TITLE
WARNING:root:could not open file'/etc/apt/sources.list'

### ISSUE THREAD

**Issue by 1043717432** [rytilahti/python-mirobo#6]
After installing virtualenv, exit virtualenv, and then run mirobo discover,
An error has occurred:
WARNING:root:could not open file'/etc/apt/sources.list'
Please help solve!
Question 2: download a good python-mirobo-master.zip is not unpacked into the homeassistant folder? A detailed tutorial?
Thank you

**Comment by rytilahti** [comment]
You should run it inside virtualenv, although that error message doesn't sound to be coming from this module. There's no reason why this module would try to access sources.list. How did you do the install? Running ```pip install python-mirobo```?

To install the homeassistant component, the simplest way is to create a symlink:
```
mkdir -p ~/.homeassistant/custom_components/switch/
ln -s /home/user/PATH_TO_SOURCE/custom_components/switch/mirobo.py ~/.homeassistant/custom_components/switch/
```
or copy the file from repository over to that directory and then restart the homeassistant. The source path needs to be adjusted depending on where you have extracted the zip.

**Comment by 1043717432** [comment]
@rytilahti  Hello I install the following commands:
#sudo Su -s /bin/bash homeassistant
#source /srv/homeassistant/bin/activate
#pip3 install python-mirobo
Then exit
Then I started executing: mirobo discover
There was an error.

**Comment by 1043717432** [comment]
@rytilahti  

The tutorial tells you: reset the robot, connect its network notification (rockrobo-XXXX) and run the following command: mirobo discover.
This step is to use the laptop WiFi connection xiaoMI sweeping robot WiFi configuration? PI is not installed on the mirobo?
