### ISSUE TITLE
Hello Thank you ！

### ISSUE THREAD

**Issue by 1043717432** [rytilahti/python-mirobo#7]
Hello
Thank you for your sharing! Can you create again Xiaomi, WiFi, plug, Xiaomi, table, lamp? I've already found their token!

**Comment by chrido** [comment]
See here: https://github.com/lazcad/homeassistant

**Comment by rytilahti** [comment]
It all depends on the device, the one @chrido mentioned works with the gateway device, then there's https://github.com/rytilahti/python-yeelightbt for the bedside bluetooth lamp. The table lamp could/should work with https://gitlab.com/stavros/python-yeelight / https://github.com/skorokithakis/yeecli .

Support for those devices is not at the moment in the scope of this project, sorry.

**Comment by 1043717432** [comment]
thank you!
